version: '3'

services:
  invoices-database:
    container_name: invoices-database
    image: bitnami/postgresql:latest
    ports:
      - '5483:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
